dirs:
    train:
        data: /data/sxu/easton/data/AISHELL/train_phone_67.csv
        tfdata: /data/sxu/easton/data/AISHELL/tfdata/train
    dev:
        data: /data/sxu/easton/data/AISHELL/dev_phone_1k.csv
        tfdata: /data/sxu/easton/data/AISHELL/tfdata/dev_1k
    test:
        data: /data/sxu/easton/data/AISHELL/test_phone_67.csv
    type: csv
    vocab: /data/sxu/easton/data/AISHELL/phones_67.txt

data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 5
    downsample: 2
    add_delta: True
    unit: phone

model:
    G:
        structure: fc
        num_hidden: 128
        num_layers: 1
        # structure: gru
        # num_hidden: 128
        # num_layers: 1
        # dropout: 0.5

opti:
    type: adam
    lr: 0.0004

dev_step: 50
decode_step: 50
save_step: 50

gpus: '0'
batch_size: 1800
num_supervised:
num_batch_tokens: 80000
bucket_boundaries: 238,300,372,437,800
seed: 8

lambda_fs: 0.0001
