dirs:
    train:
        data: /home/user/easton/data/AISHELL/train_phone_67.csv
        # data: /home/user/easton/data/AISHELL/tfdata/train_39/1.csv
        tfdata: /home/user/easton/data/AISHELL/tfdata/train_67
    dev:
        data: /home/user/easton/data/AISHELL/dev_phone_1k.csv
        tfdata: /home/user/easton/data/AISHELL/tfdata/dev_1k
    test:
        data: /home/user/easton/data/AISHELL/test_phone_67.csv
    type: csv
    vocab: /home/user/easton/data/AISHELL/phones_67.txt
    ngram: /home/user/easton/projects/asr-tf2/data/110k_67.ngram
    # ngram: /home/user/easton/projects/asr-tf2/data/110k_67.10gram
    # restore: /home/user/easton/projects/EODM/models/aishell_phone67/checkpoint/\
    lm_config: /home/user/easton/projects/EODM/configs/aishell_lm2.yaml

data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 5
    downsample: 2
    add_delta: True
    unit: phone
    full_align: True
    ngram: 5
    top_k: 1000
    k: 1000

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 256
    num_layers: 2

opti:
    type: adam
    warmup_steps: 500
    peak: 0.0008
    decay_steps: 10000
    # beam_size: 50
    num_threads: 8

dev_step: 200
decode_step: 200
save_step: 100
fs_step: 80

gpus: '0'
# gpus: '0,1,2,3'
num_batch_tokens: 250000
# batch_size: 600
batch_size: 1000
bucket_boundaries: 161,182,202,223,245,269,298,336,431,726,1000

num_epochs: 100000
num_steps: 500000

length_penalty_weight: 0.0
lambda_l2: 0.0
lambda_fs: 0.00001

grad_clip_global_norm: 0.0
