dirs:
    train:
        data: /home/user/easton/data/AISHELL/train_phone_67.csv
        # data: /home/user/easton/data/AISHELL/tfdata/train_39/1.csv
        tfdata: /home/user/easton/data/AISHELL/tfdata/train_67
    dev:
        data: /home/user/easton/data/AISHELL/test_phone_67.csv
        tfdata: /home/user/easton/data/AISHELL/tfdata/dev_67
    test:
        data: /home/user/easton/data/AISHELL/test_phone_67.csv
    type: csv
    vocab: /home/user/easton/data/AISHELL/phones_67.txt
    # ngram: /home/user/easton/projects/asr-tf2/data/110k_67.ngram
    ngram: /home/user/easton/projects/asr-tf2/data/110k_67.6gram
    # restore: /home/user/easton/projects/EODM/models/aishell_phone67/init_checkpoint/

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 10
    downsample: 4
    add_delta: False
    unit: phone
    full_align: True
    ngram: 6
    top_k: 3000
    k: 3000

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 256
    num_layers: 3

opti:
    lr: 0.005
    population: 50
    sigma: 0.05

dev_step: 10
decode_step: 50
save_step: 50

gpus: '3'
# gpus: '0,1,2,3'
num_batch_tokens: 120000
batch_size: 3000
batch_multi: 5
# batch_size: 1000
bucket_boundaries: 81,91,101,111,122,134,149,169,224,363,1000

num_epochs: 100000
num_steps: 500000

length_penalty_weight: 0.0
lambda_l2: 0.0
lambda_fs: 0.000005

grad_clip_global_norm: 0.0
