dirs:
    train:
        data: /home/user/easton/data/AISHELL/train_phone_5k.csv
        # data: /home/user/easton/data/AISHELL/tfdata/train_39/1.csv
        tfdata: /home/user/easton/data/AISHELL/tfdata/train_5k
    dev:
        data: /home/user/easton/data/AISHELL/test_phone_67.csv
        tfdata: /home/user/easton/data/AISHELL/tfdata/dev_67
    test:
        data: /home/user/easton/data/AISHELL/test_phone_67.csv
    type: csv
    vocab: /home/user/easton/data/AISHELL/phones_67.txt
    ngram: /home/user/easton/projects/EODM/data/5k_67.ngram
    # ngram: /home/user/easton/projects/EODM/data/5k_4gram_67.ngram
    # ngram: /home/user/easton/projects/EODM/data/5k_67.2gram
    # ngram: /home/user/easton/projects/EODM/data/5k_67.3gram
    # restore: /home/user/easton/projects/EODM/models/aishell_phone_5k/checkpoint/

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 5
    downsample: 4
    add_delta: True
    unit: phone
    full_align: True
    ngram: 5
    top_k: 1000
    k: 1000

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 128
    num_layers: 1

opti:
    type: adam
    warmup_steps: 50
    peak: 0.002
    decay_steps: 1000
    beam_size: 1
    # beam_size: 50
    num_threads: 8

dev_step: 100
decode_step: 50
save_step: 50

gpus: '3'
# gpus: '0,1,2,3'
num_batch_tokens: 120000
batch_size: 1000
# batch_size: 1000
bucket_boundaries: 81,91,101,111,122,134,149,169,224,363,1000

num_epochs: 100000
num_steps: 500000

length_penalty_weight: 0.0
lambda_l2: 0.0
lambda_fs: 0.0000005

grad_clip_global_norm: 0.0
