dirs:
    train:
        data: /data/sxu/easton/data/AISHELL/train_phone_9k.csv
        # data: /data/sxu/easton/data/AISHELL/tfdata/train_39/1.csv
        tfdata: /data/sxu/easton/data/AISHELL/tfdata/train_9k
    dev:
        data: /data/sxu/easton/data/AISHELL/dev_phone_1k.csv
        tfdata: /data/sxu/easton/data/AISHELL/tfdata/dev_1k
    test:
        data: /data/sxu/easton/data/AISHELL/test_phone_67.csv
    type: csv
    vocab: /data/sxu/easton/data/AISHELL/phones_67.txt
    ngram: /data/sxu/easton/data/AISHELL/9k.5gram
    # restore: /data/sxu/easton/projects/EODM/models/aishell_phone_9k/checkpoint_supervised/

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 5
    downsample: 3
    add_delta: True
    unit: phone
    ngram: 5
    top_k: 8000
    k: 8000

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 150
    num_layers: 1

opti:
    type: adam
    warmup_steps: 50
    peak: 0.01
    decay_steps: 1000

dev_step: 100
decode_step: 100
save_step: 100
fs_step: 100

gpus: '0,1,2,3'
# gpus: '1,2,3'
batch_size: 2000
batch_multi: 1
num_batch_tokens: 120000
batch_size: 500
# batch_size: 1000
bucket_boundaries: 91,111,134,169,303,1000

num_epochs: 100000
num_steps: 500000

length_penalty_weight: 0.0
lambda_fs: 0.00001

grad_clip_global_norm: 0.0
