dirs:
    train:
        data: /data/sxu/easton/data/AISHELL/train_phone_67.csv
        # data: /data/sxu/easton/data/AISHELL/tfdata/train_39/1.csv
        tfdata: /data/sxu/easton/data/AISHELL/tfdata/train_13_5_1_1
    dev:
        data: /data/sxu/easton/data/AISHELL/dev_phone_1k.csv
        tfdata: /data/sxu/easton/data/AISHELL/tfdata/dev_1k_13_5_1_1
    test:
        data: /data/sxu/easton/data/AISHELL/test_phone_67.csv
    lm:
        data: /data/sxu/easton/data/AISHELL/train_phone.txt
    type: csv
    vocab: /data/sxu/easton/data/AISHELL/phones_67.txt
data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 5
    downsample: 1
    add_delta: True
    unit: phone

model:
    G:
        structure: fc
        num_hidden: 512
        num_layers: 2
    D:
        num_hidden: 512
        num_blocks: 5

opti:
    type: adam
    D_G_rate: 1
    G:
        lr: 0.0005
    D:
        lr: 0.0005

dev_step: 50
decode_step: 50
save_step: 50

gpus: '0'
# gpus: '1,2,3'
batch_size: 250
num_batch_tokens: 80000
bucket_boundaries: 238,300,372,437,800
num_epochs: 100000
num_steps: 500000
seed: 8

lambda_fs: 0.00005
lambda_gp: 10.0
