dirs:
    train:
        data: /data/sxu/easton/data/AISHELL/train_phone_67.csv
        # data: /data/sxu/easton/data/AISHELL/tfdata/train_39/1.csv
        tfdata: /data/sxu/easton/data/AISHELL/tfdata/train
    dev:
        data: /data/sxu/easton/data/AISHELL/dev_phone_1k.csv
        tfdata: /data/sxu/easton/data/AISHELL/tfdata/dev_1k
    # dev:
    #     data: /data/sxu/easton/data/AISHELL/test_phone_67.csv
    #     tfdata: /data/sxu/easton/data/AISHELL/tfdata/dev_67
    test:
        data: /data/sxu/easton/data/AISHELL/test_phone_67.csv
    type: csv
    vocab: /data/sxu/easton/data/AISHELL/phones_67.txt
    ngram: /data/sxu/easton/data/AISHELL/110k_67.ngram
    # ngram: /data/sxu/easton/projects/asr-tf2/data/110k_67.6gram
    # restore: /data/sxu/easton/projects/EODM/models/aishell_phone67/init_checkpoint/

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 5
    downsample: 3
    add_delta: True
    unit: phone
    ngram: 5
    top_k: 8000
    k: 8000

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 160
    num_layers: 1

opti:
    lr: 0.002
    population: 100
    sigma: 0.005

dev_step: 50
decode_step: 100
save_step: 50
fs_step: 100

# gpus: '3'
gpus: '0,1,2,3'
num_batch_tokens: 120000
batch_size: 600
batch_multi: 10
# batch_size: 1000
bucket_boundaries: 81,91,101,111,122,134,149,169,224,363,1000

num_epochs: 100000
num_steps: 500000

length_penalty_weight: 0.0
lambda_l2: 0.0
lambda_fs: 0.00001

grad_clip_global_norm: 0.0
