dirs:
    exp: hksut
    train:
        scp: /data/sxu/easton/data/hkust/feats_3x.scp
        trans: /data/sxu/easton/data/hkust/char.train_3x.scp
        tfdata: /data/sxu/easton/data/hkust/tfdata/train_pinyin
    dev:
        scp: /data/sxu/easton/data/hkust/feats.dev.scp
        trans: /data/sxu/easton/data/hkust/char.dev.scp
        tfdata: /data/sxu/easton/data/hkust/tfdata/dev_pinyin
    test:
        scp: /data/sxu/easton/data/hkust/feats.dev.scp
        trans: /data/sxu/easton/data/hkust/char.dev.scp
    type: scp
    vocab: /data/sxu/easton/data/hkust/char_3673+1.vocab
    # checkpoint: /data/sxu/easton/projects/EODM/exps/hksut/hkust_CTC/checkpoint

data:
    featType: mfcc
    left_context: 0
    right_context: 0
    downsample: 1
    add_delta: False
    unit: word

model:
    encoder:
        num_hidden: 600
        num_filters: 64
opti:
    type: adam
    lr: 0.0004

dev_step: 200
decode_step: 200
save_step: 200

gpus: '0'
batch_size: 60
num_supervised:
num_batch_tokens: 25000
bucket_boundaries: 172,231,278,321,364,407,457,518,604,766,2083,4264
seed: 8
