dirs:
    train:
        data: /home/user/easton/data/LibriSpeech/train-clean-100.phone.5k.csv
        # data: /home/user/easton/data/LibriSpeech/tfdata/train_39/1.csv
        tfdata: /home/user/easton/data/LibriSpeech/tfdata/train_5k
    dev:
        data: /home/user/easton/data/LibriSpeech/dev1000.phone.csv
        tfdata: /home/user/easton/data/LibriSpeech/tfdata/dev
    test:
        data: /home/user/easton/data/LibriSpeech/dev1000.phone.csv
    type: csv
    vocab: /home/user/easton/data/LibriSpeech/phones_42.txt
    # ngram: /home/user/easton/data/LibriSpeech/100h_5k.4gram
    ngram: /home/user/easton/data/LibriSpeech/100h_5k.5gram
    # restore: /home/user/easton/projects/EODM/models/libri_phone_5k/checkpoint
    lm_config: /home/user/easton/projects/EODM/configs/libri_lm.yaml

data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 5
    downsample: 3
    add_delta: True
    unit: phone
    full_align: True
    ngram: 5
    top_k: 6000
    k: 6000

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 128
    num_layers: 1

opti:
    type: adam
    warmup_steps: 50
    peak: 0.001
    decay_steps: 1000

dev_step: 50
decode_step: 100
save_step: 100
fs_step: 50

gpus: '0'
# gpus: '0,1,2,3'
num_batch_tokens: 120000
bucket_boundaries: 81,91,101,111,122,134,149,169,224,363,1000
batch_size: 400
num_epochs: 100000
num_steps: 500000

length_penalty_weight: 0.0
lambda_fs: 0.00001

grad_clip_global_norm: 0.0
