dirs:
    train:
        data: /data/sxu/easton/data/LibriSpeech/train-clean-100.phone.1k.csv
        # data: /data/sxu/easton/data/LibriSpeech/tfdata/train_39/1.csv
        tfdata: /data/sxu/easton/data/LibriSpeech/tfdata/train_1k
    dev:
        data: /data/sxu/easton/data/LibriSpeech/dev1000.phone.csv
        tfdata: /data/sxu/easton/data/LibriSpeech/tfdata/dev
    test:
        data: /data/sxu/easton/data/LibriSpeech/dev1000.phone.csv
    type: csv
    vocab: /data/sxu/easton/data/LibriSpeech/phones_42.txt
    # ngram: /data/sxu/easton/data/LibriSpeech/100h_5k.6gram
    ngram: /data/sxu/easton/data/LibriSpeech/100h_1k.4gram
    # restore: /data/sxu/easton/projects/EODM/models/libri_phone_5k/checkpoint_supervised/

data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 10
    downsample: 4
    add_delta: False
    unit: phone
    full_align: True
    ngram: 4
    top_k: 1000
    k: 1000

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 128
    num_layers: 1

opti:
    type: adam
    warmup_steps: 100
    peak: 0.0005
    decay_steps: 1000
    beam_size: 1
    # beam_size: 50
    num_threads: 8

dev_step: 100
decode_step: 50
save_step: 20

gpus: '0'
# gpus: '0,1,2,3'
num_batch_tokens: 120000
batch_size: 1200
# batch_size: 1000
bucket_boundaries: 81,91,101,111,122,134,149,169,224,363,1000

num_epochs: 100000
num_steps: 500000

length_penalty_weight: 0.0
l1: 0.0
l2: 0.0
lambda_fs: 0.00002

grad_clip_global_norm: 0.0
