dirs:
    train:
        data: /data/sxu/easton/data/libriSpeech/libri_phone/train-clean-100.phone.random.csv
        tfdata: /data/sxu/easton/data/libriSpeech/libri_phone/tfdata/train
    dev:
        data: /data/sxu/easton/data/libriSpeech/libri_phone/dev1000.phone.csv
        tfdata: /data/sxu/easton/data/libriSpeech/libri_phone/tfdata/dev
    test:
        data: /data/sxu/easton/data/libriSpeech/libri_phone/dev1000.phone.csv
    type: csv
    vocab: /data/sxu/easton/data/libriSpeech/libri_phone/phones_42.txt

data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 5
    downsample: 2
    add_delta: True
    unit: phone
    ngram: 5
    top_k: 400
    k: 400

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 256
    num_layers: 2

opti:
    type: adam
    warmup_steps: 50
    peak: 0.0005
    decay_steps: 1000
    beam_size: 1
    # beam_size: 50
    num_threads: 8

dev_step: 100
decode_step: 50
save_step: 50
fs_step: 50

gpus: '0'
# gpus: '0,1,2,3'
num_batch_tokens: 120000
batch_size: 800
# batch_size: 1000
bucket_boundaries: 81,91,101,111,122,134,149,169,224,363,1000

num_epochs: 100000
num_steps: 500000

length_penalty_weight: 0.0
lambda_fs: 0.00001

grad_clip_global_norm: 0.0
