dirs:
    train:
        data: /data/sxu/easton/data/TIMIT/train_phone39.csv
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/train_13_5_2_3
    dev:
        data: /data/sxu/easton/data/TIMIT/test_phone39.csv
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/dev_13_5_2_3
    test:
        data: /data/sxu/easton/data/TIMIT/test_phone39.csv
    type: csv
    vocab: /data/sxu/easton/data/TIMIT/phone39.list
    ngram: /data/sxu/easton/data/TIMIT/all.5gram
    checkpoint: /data/sxu/easton/projects/EODM/exps/timit_EODM2/only250samples/checkpoint
    # restore: /data/sxu/easton/projects/EODM/models/FC_phone_level/checkpoint

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 5
    downsample: 2
    add_delta: True
    unit: phone
    ngram: 5
    top_k: 1000
    k: 1000

model:
    G:
        # structure: fc
        # num_hidden: 512
        # num_layers: 1
        structure: lstm
        num_hidden: 64
        num_layers: 1

opti:
    type: adam
    lr: 0.0004

dev_step: 50
decode_step: 200
save_step: 50

gpus: '0'
# gpus: '1,2,3'
batch_size: 1000
num_supervised: 250
num_batch_tokens: 10
bucket_boundaries: 1,2,3

lambda_fs: 0.0
