dirs:
    train:
        data: /data/sxu/easton/data/TIMIT/train_phone39.csv
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/train_13_5_2_3
    dev:
        data: /data/sxu/easton/data/TIMIT/test_phone39.csv
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/dev_13_5_2_3
    test:
        data: /data/sxu/easton/data/TIMIT/test_phone39.csv
    type: csv
    vocab: /data/sxu/easton/data/TIMIT/phone39.list

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 5
    downsample: 2
    add_delta: True
    unit: phone

model:
    G:
        # structure: fc
        # num_hidden: 512
        # num_layers: 1
        structure: lstm
        num_hidden: 128
        num_layers: 1

opti:
    type: adam
    lr: 0.0004

dev_step: 100
decode_step: 200
save_step: 100

gpus: '0'
# gpus: '1,2,3'
batch_size: 600
num_supervised: 250
num_batch_tokens: 10
bucket_boundaries: 1,2,3
