dirs:
    train:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/train/text
        # align: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/exp/mono_ali/train.phone.frame
        align: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/exp/tri3_ali/train.phone.frame
        wav_scp: /data/sxu/easton/data/TIMIT/train_wav.scp
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/train_feats_13_5_2_3
    dev:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/test/text
        align: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/exp/tri3_dev_ali/test.phone.frame
        wav_scp: /data/sxu/easton/data/TIMIT/test_wav.scp
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/test_feats_13_5_2_3
    test:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/test/text
    type: csv
    vocab: /data/sxu/easton/data/TIMIT/phone39.vocab
    # checkpoint: /data/sxu/easton/projects/EODM/exps/timit_supervised2/full_big/checkpoint

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 5
    downsample: 2
    add_delta: True
    unit: phone

model:
    G:
        structure: fc
        num_hidden: 512
        num_layers: 1

opti:
    type: adam
    lr: 0.0004

dev_step: 300
decode_step: 200
save_step: 500

gpus: '0'
# gpus: '1,2,3'
batch_size: 600
num_supervised:
num_batch_tokens: 10
bucket_boundaries: 1,2,3
