dirs:
    train:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/train/text
        # align: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/exp/tri3_ali/train.phone.frame
        align: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/exp/iter_ali/train.phone.frame
        wav_scp: /data/sxu/easton/data/TIMIT/train_wav.scp
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/train_feats
    train_supervise:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/train/text_200
        align: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/exp/tri3_ali/train_200.phone.frame
        wav_scp: /data/sxu/easton/data/TIMIT/train200_wav.scp
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/train200_feats
    dev:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/test/text
        align: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/exp/tri3_test_ali/test.phone.frame
        wav_scp: /data/sxu/easton/data/TIMIT/test_wav.scp
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/test_feats
    test:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/test/text
    lm:
        data: /data/sxu/easton/data/TIMIT/train_phone.txt
    type: csv
    vocab: /data/sxu/easton/data/TIMIT/phone39.vocab
    # checkpoint: /data/sxu/easton/projects/EODM/exps/timit_supervised/200/checkpoint

data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 5
    downsample: 1
    add_delta: True
    unit: phone

model:
    G:
        structure: fc
        num_hidden: 512
        num_layers: 1
    D:
        num_hidden: 512
        num_blocks: 5
opti:
    D_G_rate: 1
    G:
        lr: 0.0001
    D:
        lr: 0.0001

dev_step: 200
decode_step: 200
save_step: 200

gpus: '0'
batch_size: 300
num_supervised: 200
max_seq_len: 60

lambda_fs: 0.0
lambda_gp: 10.0
lambda_supervision: 5.0
