dirs:
    train:
        data: /data/sxu/easton/data/TIMIT/train_phone39.csv
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/tmp/train_39
    dev:
        data: /data/sxu/easton/data/TIMIT/test_phone39.csv
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/tmp/dev_39
    test:
        data: /data/sxu/easton/data/TIMIT/test_phone39.csv
    type: csv
    vocab: /data/sxu/easton/data/TIMIT/phone39.list
    ngram: /data/sxu/easton/data/TIMIT/all.5gram
    # restore: /data/sxu/easton/projects/EODM/models/FC_phone_level/init_checkpoint
    # restore: /data/sxu/easton/projects/EODM/models/FC_phone_level/checkpoint

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 5
    downsample: 1
    add_delta: True
    unit: word
    full_align: True
    ngram: 5
    top_k: 1000
    k: 1000

model:
    G:
        structure: fc
        num_hidden: 128
        num_layers: 1

opti:
    type: adam
    warmup_steps: 100
    peak: 0.0004
    decay_steps: 2000
    beam_size: 1

dev_step: 50
decode_step: 200
save_step: 50

gpus: '0'
# gpus: '1,2,3'
batch_size: 1000
num_supervised: 250
num_batch_tokens: 10
bucket_boundaries: 1,2,3
num_epochs: 100000
num_steps: 500000

length_penalty_weight: 0.0
lambda_fs: 0.000001

grad_clip_global_norm: 0.0
