dirs:
    train:
        data: /home/user/easton/data/TIMIT/train_phone39.csv
        tfdata: /home/user/easton/data/TIMIT/tfdata/tmp/train_39
    dev:
        data: /home/user/easton/data/TIMIT/test_phone39.csv
        tfdata: /home/user/easton/data/TIMIT/tfdata/tmp/dev_39
    test:
        data: /home/user/easton/data/TIMIT/test_phone39.csv
    type: csv
    vocab: /home/user/easton/data/TIMIT/phone39.list
    ngram: /home/user/easton/projects/EODM/all.ngram
    # restore: /home/user/easton/projects/EODM/models/FC_phone_level/init_checkpoint
    restore: /home/user/easton/projects/EODM/models/timit_es2/checkpoint

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 5
    downsample: 1
    add_delta: True
    unit: word
    full_align: True
    ngram: 5
    top_k: 1000
    k: 1000

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 128
    num_layers: 1

opti:
    lr: 0.001
    population: 50
    sigma: 0.001
    lr_fs: 0.0000005

dev_step: 5
decode_step: 10
save_step: 5
fs_step: 2000000

gpus: '0'
# gpus: '1,2,3'
batch_size: 800
batch_multi: 1
num_batch_tokens: 780000
bucket_boundaries: 238,300,372,437,800
num_epochs: 100000
num_steps: 500000

grad_clip_global_norm: 0.0
