dirs:
    train:
        data: /data/sxu/easton/data/TIMIT/train_phone39.csv
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/train_39
    dev:
        data: /data/sxu/easton/data/TIMIT/test_phone39.csv
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/dev_39
    test:
        data: /data/sxu/easton/data/TIMIT/test_phone39.csv
    type: csv
    vocab: /data/sxu/easton/data/TIMIT/phone39.list
    ngram: /data/sxu/easton/projects/EODM/all.ngram
    # restore: /data/sxu/easton/projects/EODM/models/timit_test/checkpoint
    lm_config: /data/sxu/easton/projects/EODM/configs/timit_lm.yaml

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 5
    downsample: 1
    add_delta: True
    unit: word
    full_align: True
    ngram: 5
    top_k: 1000
    k: 1000
    dim_embedding: 64

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 512
    num_layers: 1

opti:
    type: adam
    warmup_steps: 100
    peak: 0.001
    decay_steps: 1000

dev_step: 100
decode_step: 100
save_step: 100
fs_step: 100

gpus: '0'
# gpus: '1,2,3'
batch_size: 1000
num_batch_tokens: 10
bucket_boundaries: 40,50,60,70,80,90
num_epochs: 100000
num_steps: 500000

lambda_fs: 0.00001

grad_clip_global_norm: 0.0
